server:
 port: 8888

#项目访问前缀 localhost:8888/sell/...
 servlet:
  context-path: /sell

spring:
 druid:
    #jdbc:mysql://192.168.1.177:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
     url: jdbc:mysql://192.168.1.177:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
     username: root
     password: 123456
     maxActive: 30 #最大链接数
     maxWait: 10000 #获得链接的最大等待时间

 jpa:
     show-sql: true  #显示sql语句
 jackson:
   date-format: yyyy-MM-dd HH:mm:ss  #日期格式化标准
   default-property-inclusion: non_null #返回json时 忽略null
